version: "4.33.1"

services:
  upload_service:
    build: ./upload_service
    ports:
      - "8000:8000"
    # environment:
    #   - DATABASE_URL=postgresql://user:password@db:5432/your_database
    # depends_on:
    #   - db

  chat_service:
    build: ./chat_service
    ports:
      - "5000:5000"
    # environment:
    #   - DATABASE_URL=postgresql://user:password@db:5432/your_database
    # depends_on:
    #   - db

  scrape_service:
    build: ./scrape_service
    ports:
      - "6000:6000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/your_database
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: your_database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: